version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vulnreport-app
    networks:
      - vulnreport

  nginx:
    image: nginx:alpine
    container_name: vulnreport-nginx
    ports:
      - "8000:80"   # publish frontend ke port 8000
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - vulnreport

networks:
  vulnreport:
    driver: bridge
